name: AstroUI

on:
  push:
    branches: [main]
  pull_request:
  pull_request_target:
    types: [opened, edited, synchronize]
  schedule:
    - cron: "0 6 * * *"
    - cron: "0 8 * * 1"

jobs:
  CI:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
    uses: AstroNvim/.github/.github/workflows/plugin_ci.yml@main
    with:
      plugin_name: ${{ github.event.repository.name }}
      is_production: false

  Tests:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' }}
    permissions:
      contents: read
    uses: AstroNvim/.github/.github/workflows/neovim_testing.yml@main
    with:
      minimum_neovim: "0.11.0"
      stable_neovim: "0.12.4"
      cache_rotation: "1"
      timeout_minutes: 30
      enable_windows_minimum_ffi: true

  Release:
    if: ${{ github.event_name == 'push' }}
    needs: Tests
    concurrency:
      group: ${{ github.event.repository.name }}-release
      cancel-in-progress: false
    permissions:
      contents: write
      pull-requests: write
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    uses: AstroNvim/.github/.github/workflows/plugin_ci.yml@main
    with:
      plugin_name: ${{ github.event.repository.name }}
      is_production: true

  PR:
    if: ${{ github.event_name == 'pull_request_target' }}
    permissions:
      pull-requests: read
    uses: AstroNvim/.github/.github/workflows/validate_pr.yml@main
